### ISSUE TITLE
Standalone mode doesn't run

### ISSUE THREAD

**Issue by i-am-shodan** [llamafilm/tesla-http-proxy-addon#100]
### The problem

Hi,
I'm trying to get the standalone mode running as I don't run HASSIO.

I needed to make some changes to even get the container to run. These include:
* Changing the container version to latest
* Including the current working directory in the container volume mappings
* Adding a new env variable 'DEBUG'

These changes are below.
```
docker run --rm --name nginx -d -p 4430:443 -e DOMAIN="$DOMAIN" --network tesla \
    -v `pwd`/ssl:/ssl:ro \
    -v `pwd`/share:/share:ro \
    -v `pwd`/nginx/nginx_tesla.conf:/etc/nginx/conf.d/nginx_tesla.conf:ro \
    -v `pwd`/nginx/dhparams.pem:/data/dhparams.pem:ro \
    nginx

## build from source while developing proxy
# git clone https://github.com/llamafilm/tesla-http-proxy-addon.git
# docker build --build-arg BUILD_FROM=ghcr.io/home-assistant/${ARCH}-homeassistant-base tesla-http-proxy-addon/tesla_http_proxy

# start proxy container

docker run --rm --name tesla_http_proxy -p 8099:8099 -p 443:443 --network tesla \
    -v `pwd`/share:/share \
    -v `pwd`/bashio:/tmp/.bashio:ro \
    -e DOMAIN="${DOMAIN}" \
    -e CLIENT_ID="${CLIENT_ID}" \
    -e CLIENT_SECRET="${CLIENT_SECRET}" \
    -e REGION="${REGION}" \
    -e DEBUG=1 \
    -e SUPERVISOR_TOKEN="fake-token" \
    ghcr.io/llamafilm/tesla_http_proxy_${ARCH}:latest
```

The problem is now that although the containers are running the tesla_http_proxy crashes with the error
```
[17:43:27] INFO: Testing public key...

/app/run.sh: line 97: [: : integer expression expected
```

I looked in the source here is the relevant line.

![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/6901273/e4e0ec3c-cc6a-4325-824b-25f3887111d4)

Given the blank space it looks like $CURL_OUT is null or empty.

I checked the logs for the container

![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/6901273/1eec18df-d273-4f71-b277-dad223e0ae3f)

My guess is that nginx is not starting for some reason so it's not listening for requests and that curl command fails.

I jumped into the container, I can't even find the nginx binary.

It doesn't look like the standalone install has been run for a while. Can someone give me some pointers to get it running?

### What version of the addon are you using?

Docker on Linux

### What version of Home Assistant Core are you using?

2024.5.0

### What type of installation are you running?

Home Assistant Container

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model Y

### What is your domain name (FQDN)?

test.example.com

**Comment by i-am-shodan** [comment]
If I jump onto the tesla_http_proxy container and run

`curl https://test.example.com:4430 -vvv`
I get a valid response. But if I run

`curl https://test.example.com:443 -vvv`

I don't get a connection. This is because the container is turning test.example.com to the private IP of the server its on instead of the public IP. As a result the packets aren't routed to the gateway that port forwards 4430->443.

**Comment by i-am-shodan** [comment]
Adding `--add-host $DOMAIN:MY_EXTERNAL_IP \` looks like it has fixed that bug. But now I get another error

```
[18:16:39] auth:INFO: Registering Tesla account...
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.11/http/client.py", line 1298, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xb5f2e550>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='supervisor', port=80): Max retries exceeded with url: /addons/self/options/config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5f2e550>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/auth.py", line 67, in <module>
    req = requests.get('http://supervisor/addons/self/options/config',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='supervisor', port=80): Max retries exceeded with url: /addons/self/options/config (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xb5f2e550>: Failed to establish a new connection: [Errno -3] Try again'))
```

**Comment by i-am-shodan** [comment]
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/6901273/11d47243-d50d-4077-8bcb-a2d404f646f0)

This code is what is causing the issue. The only problem is I don't have a supervisor, and wont. I'm pretty sure standalone won't work with this in place.

**Comment by i-am-shodan** [comment]
Going to roll back to 1.3.7

**Comment by i-am-shodan** [comment]
Using 1.3.7 and a much simpler DNS setup gets something running. The only problem now is that when I try and get oauth it redirects me to mydomain/callback where I get a 404. Shouldn't the nginx container be sending this to the tesla_http_proxy?

**Comment by i-am-shodan** [comment]
Ok I've added a proxy pass line to the nginx config and now the auth flow works enough to be a token on screen.

After changing the bashio line I can even use the proxy to send commands.

It's clear that the version checked into master can't be used without a hassio install. I suggest you remove/change the documentation in the Readme.md and provide a link to an old tag or something.

**Comment by darek-margas** [comment]
> ![image](https://private-user-images.githubusercontent.com/6901273/333901514-11d47243-d50d-4077-8bcb-a2d404f646f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzg3NjMsIm5iZiI6MTcxNjc3ODQ2MywicGF0aCI6Ii82OTAxMjczLzMzMzkwMTUxNC0xMWQ0NzI0My1kNTBkLTQwNzctOGJjYi1hMmQ0MDRmNjQ2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMDI1NDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzAyYmI4MTNjNGFkNmY0NTMzMjBjNDcyMTg4NjY3ODkyZWQ4NzRhOTdlZTU3YmRiYWEzMGE4MDllODY3NWYyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A6eUMqq9GLi0ebWl0kIY30vWw8Zls2NJBkHrzWZCs14)
> 
> This code is what is causing the issue. The only problem is I don't have a supervisor, and wont. I'm pretty sure standalone won't work with this in place.

How about false_token from example?

**Comment by chrismcneil** [comment]
I couldn't get as far as you have but I did come across https://github.com/iainbullock/tesla-http-proxy-docker/

**Comment by i-am-shodan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/6901273/333901514-11d47243-d50d-4077-8bcb-a2d404f646f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzg3NjMsIm5iZiI6MTcxNjc3ODQ2MywicGF0aCI6Ii82OTAxMjczLzMzMzkwMTUxNC0xMWQ0NzI0My1kNTBkLTQwNzctOGJjYi1hMmQ0MDRmNjQ2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMDI1NDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzAyYmI4MTNjNGFkNmY0NTMzMjBjNDcyMTg4NjY3ODkyZWQ4NzRhOTdlZTU3YmRiYWEzMGE4MDllODY3NWYyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A6eUMqq9GLi0ebWl0kIY30vWw8Zls2NJBkHrzWZCs14)
> 
> > 
> 
> > This code is what is causing the issue. The only problem is I don't have a supervisor, and wont. I'm pretty sure standalone won't work with this in place.
> 
> 
> 
> How about false_token from example?

That won't work. It still makes a request to supervisor which fails and throws an exception which kills the container

**Comment by darek-margas** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/6901273/333901514-11d47243-d50d-4077-8bcb-a2d404f646f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Nzg3NjMsIm5iZiI6MTcxNjc3ODQ2MywicGF0aCI6Ii82OTAxMjczLzMzMzkwMTUxNC0xMWQ0NzI0My1kNTBkLTQwNzctOGJjYi1hMmQ0MDRmNjQ2ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMDI1NDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzAyYmI4MTNjNGFkNmY0NTMzMjBjNDcyMTg4NjY3ODkyZWQ4NzRhOTdlZTU3YmRiYWEzMGE4MDllODY3NWYyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A6eUMqq9GLi0ebWl0kIY30vWw8Zls2NJBkHrzWZCs14)
> > 
> > 
> > > 
> > 
> > 
> > > This code is what is causing the issue. The only problem is I don't have a supervisor, and wont. I'm pretty sure standalone won't work with this in place.
> > 
> > 
> > How about false_token from example?
> 
> That won't work. It still makes a request to supervisor which fails and throws an exception which kills the container

Interesting. I was able to install it standalone, however, not using example script. I run docker and just images I want. 
It was early image, the one generating token as well. I made it with key installed in the car and container happily running, even later versions but it failed anyway, trying to refresh valid token with no success. I had no courage to continue and uninstalled integration as I don't need it anyway but I am sure I was able to run container without crash.

**Comment by llamafilm** [comment]
The script worked before, but you broke it by changing `1.3.6` to `latest`.  I've made some changes in #105 to keep it working with the current version.

**Comment by i-am-shodan** [comment]
I also needed to use absolute paths for volumes.
