### ISSUE TITLE
ERROR: HTTP status code

### ISSUE THREAD

**Issue by Dester20** [llamafilm/tesla-http-proxy-addon#102]
### The problem

I have the problem, that I can't connect to the car, but in the log files an error occurs

/app/run.sh: line 97: [: : integer expression expected
[20:57:49] ERROR: HTTP status code 

I can't handle with this error and no other one has this kind of error... 
Can you help me please?

### What version of the addon are you using?

2.25

### What version of Home Assistant Core are you using?

2024.5.4

### What type of installation are you running?

Home Assistant OS

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model Y

### What is your domain name (FQDN)?

dester20.duckdns.org

### Paste the log output from the addon here

```text
[20:57:49] INFO: Found existing keypair
[20:57:49] INFO: Testing dester20.duckdns.org for an associated IP address...
dester20.duckdns.org has address 217.88.129.50
dester20.duckdns.org mail is handled by 50 dester20.duckdns.org.
[20:57:49] INFO: Found an IP address for dester20.duckdns.org
[20:57:49] INFO: Testing public key...

/app/run.sh: line 97: [: : integer expression expected
[20:57:49] ERROR: HTTP status code ; Sleeping 2 minutes before retry.
```

**Comment by baylanger** [comment]
Working to fix that run.sh error but here's what shows up when running it manually from my place:

```
curl: (35) OpenSSL/3.3.0: error:0A000458:SSL routines::tlsv1 unrecognized name
```

You can also use, for example, [this site](https://www.ssllabs.com/ssltest/) to test the SSL connection.

Do you have any special setup? It looks like the connection from the Internet to your server isn't going to the right port.. perhaps a non-SSL port like 80?!

**Comment by Dester20** [comment]
On Friday it all works fine, Saturday not... Between I don't charge anything in my configuration...

Is it possible Tesla locked me out?
On developer.tesla.com the application status is active...

Port 80, can I check this, if it is a non SSL port?

**Comment by baylanger** [comment]
Here's the output from openssl , definitely something wrong with the SSL service.

```
$ openssl s_client -connect dester20.duckdns.org:443
Connecting to 217.88.129.50
CONNECTED(00000003)
283B0879E57F0000:error:0A000458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:ssl/record/rec_layer_s3.c:907:SSL alert number 112
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 328 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Comment by baylanger** [comment]
@llamafilm because curl can't output the SSL error with the -s (silent) option, I'm adding in run.sh before the curl section a SSL certificate check using openssl.  I tried to remove the -s option to curl but it's a PITA cuz  it outputs a progress bar that screws up the HTTP code.

**Comment by Dester20** [comment]
Thanks a lot, now it works 

Kind regards 😁

**Comment by Dester20** [comment]
Works well
