### ISSUE TITLE
Regular expression does not fit my client secret

### ISSUE THREAD

**Issue by mrpajzl** [llamafilm/tesla-http-proxy-addon#110]
### The problem

Trying to configure the addon but it does not allow me to use my client secret unfortunately. 
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/29248446/039a68b1-dc9c-44e6-8cc2-320515dcda2f)
Any idea what the issue might be? Maybe a change in tesla secret format?

### What version of the addon are you using?

2.2.7

### What version of Home Assistant Core are you using?

2024.5.0

### What type of installation are you running?

Home Assistant OS

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model Y 2024

### What is your domain name (FQDN)?

ihopeitsnotneccesary.homeassistant.com

**Comment by llamafilm** [comment]
Can you share the secret? And then change it in the Tesla developer site.

**Comment by mrpajzl** [comment]
Not sure how I can change it but I can manipulate the original one so it maintains the format but change the letters and numbers
ta-secret.*1X+dOBTU&nov8d

**Comment by llamafilm** [comment]
The regex validation is actually on the domain field, not the client secret.
