### ISSUE TITLE
Unable to Share Vehicle: This third party isn't registered with Tesla. We can't grant them access at the time

### ISSUE THREAD

**Issue by vdiogo** [llamafilm/tesla-http-proxy-addon#119]
### The problem

Followed the steps [here](https://www.smartmotion.life/2024/04/06/tesla-integration-with-home-assistant/?v=6cc98ba2045f) and can't seem to get the Tesla custom integration to work:
<img width="989" alt="image" src="https://github.com/llamafilm/tesla-http-proxy-addon/assets/24878195/ac12dd8d-91cc-4acc-b052-873a2365e4c1">

The issue seems to be related with step 5.11 from the url above that is why I raised the issue here:
`5.11 Navigate back to the Tesla HTTP Proxy add on screen and choose ‘Enrol public key in your vehicle’ and follow the instructions.`

As a message shows in the Tesla app (translated to EN as my app is in PT) "Unable to Share Vehicle: This third party isn't registered with Tesla. We can't grant them access at the time".

### What version of the addon are you using?

 2.2.7

### What version of Home Assistant Core are you using?

core-2024.6.3

### What type of installation are you running?

Home Assistant OS

### What version of Tesla integration are you using?

3.20.5

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model Y 2023

### What is your domain name (FQDN)?

tesla.v4-barra.com

### Paste the log output from the addon here

```text
HTTP/2 404 
date: Mon, 17 Jun 2024 18:35:44 GMT
curl: (22) The requested URL returned error: 404
content-type: text/plain; charset=utf-8
Warning: Problem (retrying all errors). Will retry in 600 seconds. 4 retries 
Warning: left.
content-length: 14
referrer-policy: no-referrer
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=UsFEN5kjzfS6dTy9hbJknO8KhjRygaDEHwR62kQ%2FdvhMJi6rerx6QKc4B28JPG8QUd5RIfa6hTP%2Bv5NLj2QRKcZC3%2FBQguwXI8AiwL6Y%2FsYt5gIJEaCXYTGH7a%2F64F4EQHpQZes%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 89552420cef152bd-LHR
alt-svc: h3=":443"; ma=86400
```

**Comment by llamafilm** [comment]
It would help if you share the full addon log. From what I can see here, this sounds like a problem on your Cloudflare config, so the public key is not accessible. You’ll need to fix that before proceeding, as it says in the log output.

**Comment by vdiogo** [comment]
Thanks for the prompt answer. I reviewed the Cloudflare configuration, and followed the wiki [here](https://github.com/llamafilm/tesla-http-proxy-addon/wiki/Cloudflare-Argo-Tunnel) this time.
After re-starting the Tesla HTTP proxy add-on, I get the same logs repeatedly:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service webui: starting
s6-rc: info: service webui successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[10:54:22] webui:INFO: Starting Flask server for Web UI...
[10:54:22] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.30.33.3:8099
[10:54:22] werkzeug:INFO: Press CTRL+C to quit
[10:54:23] INFO: Found existing keypair
[10:54:23] INFO: Testing public key...
HTTP/2 404 
date: Tue, 18 Jun 2024 09:54:24 GMT
content-type: text/plain; charset=utf-8
content-length: 14
referrer-policy: no-referrer
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=pDIIiFmCtnvLq5tt%2FVmCA2ot%2BYRg5%2FMJovwqqRqsYzC4lrwlGcsbgzaAdO%2BDvAXpkOcNGZ68W4mVBrrcJJJu9JOAFHcAtnCzoBm8V2dan2KLDqvOtFyGSwrH4ul9i0NRZCaVFgE%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 895a65d3c9ab068a-LHR
alt-svc: h3=":443"; ma=86400```

**Comment by vdiogo** [comment]
Followed trouble shooting steps [here](https://github.com/llamafilm/tesla-http-proxy-addon/wiki/Read-this-before-asking-for-help#unable-to-grant-vehicle-access-to-a-third-party-at-this-time):
**- Checked DNS**
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/24878195/36947664-4220-4333-b3ef-c33961a712cd)
**- Checked if HA could resolve the address**
<img width="610" alt="image" src="https://github.com/llamafilm/tesla-http-proxy-addon/assets/24878195/b62aa5c7-e56b-4aee-bf60-3c459f9ced7c">
**- Tested public key" button in the Web UI and iOS app**
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/24878195/3f4a480f-a75b-451b-9a66-8baa2fc7d06e)

<img width="654" alt="image" src="https://github.com/llamafilm/tesla-http-proxy-addon/assets/24878195/49eccc53-b763-4b19-b3ce-7bea1ba72fd5">

**Comment by llamafilm** [comment]
Have you also restarted nginx addon? That is necessary so it loads the new config.

**Comment by vdiogo** [comment]
> Have you also restarted nginx addon? That is necessary so it loads the new config.

Yes: I had to reconfigure the add-on, so stopped it, re-configured it and started it again.

These are the logs captured just now:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service crond: starting
s6-rc: info: service crond successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[09:57:30] INFO: Generating dhparams (this will take some time)...
Generating DSA parameters, 4096 bit long prime
...+..+..+..+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*
.....+..+......+..........+.......+...................+.......+....................+...........+...+....+.........+...+....................+..+..+......+..+..+....+.....+........+..+...................+.........................+......+.......+.......+............+....................+..........+.....+.....+....+...+.+.............+.....+.............+.....+.+............+.+..+...+..+........+....+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*
[09:57:56] INFO: Creating 'cloudflare.conf' for real visitor IP address...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   230  100   230    0     0   1077      0 --:--:-- --:--:-- --:--:--  1084
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   104  100   104    0     0    570      0 --:--:-- --:--:-- --:--:--   574
```

**Comment by vdiogo** [comment]
I tried on another HA instance (LXC container) and worked fine this time. Many thanks for the guide in the wiki, it helped a lot in.
