### ISSUE TITLE
Impossible to send Tesla commands control, 

### ISSUE THREAD

**Issue by InnoGreenTech** [llamafilm/tesla-http-proxy-addon#122]
### The problem

Hello, I can send command to control the charge of Tesla car. 

I have this way:

Server returned 429: Too Many Requests: Retry in 49200 seconds

Best regards

### What version of the addon are you using?

 2.2.8

### What version of Home Assistant Core are you using?

2024.6.4

### What type of installation are you running?

Home Assistant OS

### What version of Tesla integration are you using?

v3.24.0

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

MODEL 3 2023

### What is your domain name (FQDN)?

https://tesla.innogreentech.fr

### Paste the log output from the addon here

```text
2024-06-23T12:32:08+02:00 [debug] Server returned 429: Too Many Requests: Retry in 48472 seconds

2024-06-23T12:32:08+02:00 [warn ] [85f39bd5def6ef708741ad802e5de634] Terminal transmission error: Retry in 48472 seconds

2024-06-23T12:32:08+02:00 [error] Returning error Too Many Requests
```

**Comment by llamafilm** [comment]
This is not a bug. API rate limits are described here: https://developer.tesla.com/docs/tesla-fleet-api#membership-levels

**Comment by InnoGreenTech** [comment]
> This is not a bug. API rate limits are described here: https://developer.tesla.com/docs/tesla-fleet-api#membership-levels

Yes thanks ,i have find it two. 

<html>
<body>

Device data limits | 200 requests / vehicle / day
-- | --
Commands limits | 50 requests / vehicle / day
Wake limits | 15 requests / vehicle / day
Charging commands | 5 request / vehicle / day
Energy Device data limits | 50k API requests / dayAnd5 API requests / secAnd1 API request / energy site / 5 min.
Energy Settings limits | 50k API requests / dayAnd5 API requests / secAnd5 API requests / energy site / dayAnd1 tariff change / energy site / month.


</body>
</html>
