### ISSUE TITLE
404 error when starting Tesla HTTP Proxy

### ISSUE THREAD

**Issue by jnicolaes** [llamafilm/tesla-http-proxy-addon#124]
### The problem

I've configured the subdomain,made sure the A record is setup (DuckDNS). Configured let's encrypt to sign the certificate for the subdomain. The Fleet API application is setup and I'm trying to start the Tesla HTTP Proxy. It's throwing this error: 

curl: (22) The requested URL returned error: 404
Warning: Problem (retrying all errors). Will retry in 1 seconds. 14 retries 
Warning: left.
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
Server: 
X-Frame-Options: SAMEORIGIN
Content-Length: 14
Date: Tue, 02 Jul 2024 07:35:24 GMT

I've enabled verbose logging but not sure which URL it's reaching out to to confirm why it's not working.

I'm using 2.2.8

### What version of the addon are you using?

2.2.8

### What version of Home Assistant Core are you using?

2024.4.4

### What type of installation are you running?

Home Assistant OS

### What version of Tesla integration are you using?

v3.24.0

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model Y 2024

### Paste the log output from the addon here

```text
s6-rc: info: service webui: starting
s6-rc: info: service webui successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[09:42:51] webui:INFO: Starting Flask server for Web UI...
[09:42:51] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.30.33.6:8099
[09:42:51] werkzeug:INFO: Press CTRL+C to quit
[09:42:52] INFO: Found existing keypair
[09:42:52] INFO: Testing public key...
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
Server: 
X-Frame-Options: SAMEORIGIN
Content-Length: 14
Date: Tue, 02 Jul 2024 07:42:52 GMT

curl: (22) The requested URL returned error: 404
Warning: Problem (retrying all errors). Will retry in 1 seconds. 14 retries 
Warning: left.
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
Server: 
X-Frame-Options: SAMEORIGIN
Content-Length: 14
Date: Tue, 02 Jul 2024 07:42:53 GMT

curl: (22) The requested URL returned error: 404
Warning: Problem (retrying all errors). Will retry in 2 seconds. 13 retries 
Warning: left.
```

**Comment by llamafilm** [comment]
It doesn’t look like debug logging is enabled. You have to restart the add on after changing that setting.

The URL it’s trying is https://tesla.observantenweg78.duckdns.org/.well-known/appspecific/com.tesla.3p.public-key.pem
That link is actually working fine for me, but maybe the behavior is different from within your local network. Are you using the recommended config with Nginx addon?

**Comment by jnicolaes** [comment]
Did setup NGINX, here's the logs and settings:
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service crond: starting
s6-rc: info: service crond successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[13:02:17] INFO: Running nginx...

<img width="1006" alt="image" src="https://github.com/llamafilm/tesla-http-proxy-addon/assets/701189/fbaa8533-2255-45c9-979e-369e563ccbf0">

I do have external access enabled though, not sure if this is conflicting. That URL is working on my mobile even on local network, but when I try to open it on my laptop it says not found. Even if I setup a hotspot with my mobile, to bypass the home network it gives the same error.

**Comment by llamafilm** [comment]
What do you see when the url works on your mobile? If it’s an iOS device, you should see some message about downloading a config profile and no SSL errors. 
I noticed dnschecker.com shows several servers haven’t yet pickup up your domain so you might just need to wait a day or 2 for that to propagate.

**Comment by jnicolaes** [comment]
Yes, it asks to download config profile, no SLL error. When I download the profile it says it's invalid. The observantenweg78.duckdns.org domain is being used for half a year already does it still need propagation?

**Comment by jnicolaes** [comment]
Additional info. I've done a nsLookup on my laptop and that seems fine. When I perform a cURL it's mentioning the it's just not found: 

curl -v https://tesla.observantenweg78.duckdns.org/.well-known/appspecific/com.tesla.3p.public-key.pem
* processing: https://tesla.observantenweg78.duckdns.org/.well-known/appspecific/com.tesla.3p.public-key.pem
*   Trying 83.84.86.73:443...
* Connected to tesla.observantenweg78.duckdns.org (83.84.86.73) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /Users/jeromenicolaes/anaconda3/ssl/cacert.pem
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=observantenweg78.duckdns.org
*  start date: Jul  1 16:09:47 2024 GMT
*  expire date: Sep 29 16:09:46 2024 GMT
*  subjectAltName: host "tesla.observantenweg78.duckdns.org" matched cert's "tesla.observantenweg78.duckdns.org"
*  issuer: C=US; O=Let's Encrypt; CN=R11
*  SSL certificate verify ok.
* using HTTP/1.x
> GET /.well-known/appspecific/com.tesla.3p.public-key.pem HTTP/1.1
> Host: tesla.observantenweg78.duckdns.org
> User-Agent: curl/8.2.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Referrer-Policy: no-referrer
< X-Content-Type-Options: nosniff
< Server: 
< X-Frame-Options: SAMEORIGIN
< Content-Length: 14
< Date: Tue, 02 Jul 2024 14:51:33 GMT
< 
* Connection #0 to host tesla.observantenweg78.duckdns.org left intact
404: Not Found%

**Comment by llamafilm** [comment]
Okay, it looks like DNS and SSL are fine and the problem is somewhere in the addon or nginx.  Enable the nginx debug log and restart it; it should show something about a 404.

**Comment by jnicolaes** [comment]
Thanks for your help so far. It seems NGINX doesn't really have a verbose logging. The logs as shared earlier, is basically all I'm getting.
