### ISSUE TITLE
Regular expression issue on FQDN field

### ISSUE THREAD

**Issue by Niall-Scott** [llamafilm/tesla-http-proxy-addon#134]
### The problem

I am seeing the same issue reported on for the client secret but this issue is actually on the FQDN:
![image](https://github.com/user-attachments/assets/bbf2c355-55f9-4b77-b48d-5f185279e14d)
It appears (I am no expert) the issue is the regex is expecting only letters and numbers but this means the :// in https:// is causing the failure.

If I remove the https:// then the addon works but when I try to add it says the domain is not recognised, I have assumed that is because the domains dont match.

Thanks for all your work on building and maintaining this.

### What version of the addon are you using?

 2.2.8

### What version of Home Assistant Core are you using?

2024.6.4

### What type of installation are you running?

Home Assistant OS

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Model 3

### What is your domain name (FQDN)?

not relevant

**Comment by llamafilm** [comment]
You need to enter it without https, as it says in the help text on that field. 
![image](https://github.com/user-attachments/assets/1a33eb75-27d0-42c9-88b7-e1769b34a7aa)
