### ISSUE TITLE
DNS problems

### ISSUE THREAD

**Issue by jorgeal94** [llamafilm/tesla-http-proxy-addon#20]
Hi, trying to install the addon, I´m using cloudflare and got some problems with the config:

On cloudflare I configured one argo tunnel with 2 public hostnames pointing to my local IP for HAOS(192.168.0.2:8123)
the hostnames are tesla.example.es and home.example.es (where example is my hosting name)
Instales NGINX , and configured with: 
Domain: tesla.example.es
Cloudflare ON
customize: as the DOCS.

When starts on logs says:   " nginx: [warn] conflicting server name "tesla,example.es" on 0.0.0.0:443, ignored  "

so whe I try to see https://tesla.example.es/.well-known/appspecific/com.tesla.3p.public-key.pem   I got 404 error.

Nmap shows this:

Starting Nmap 7.94 ( https://nmap.org ) at 2024-03-10 17:30 Hora estßndar romance
Nmap scan report for EXAMPLE.rmxtech.es (188.114.97.5)
Host is up (0.017s latency).
Other addresses for tesla.EXAMPLE.es (not scanned): -----

PORT    STATE SERVICE
443/tcp open  https
| ssl-cert: Subject: commonName=EXAMPLE.es
| Subject Alternative Name: DNS:EXAMPLE.es, DNS:*.EXAMPLE.es
| Issuer: commonName=GTS CA 1P5/organizationName=Google Trust Services LLC/countryName=US
| Public Key type: rsa
| Public Key bits: 2048
| Signature Algorithm: sha256WithRSAEncryption
| Not valid before: 2024-03-07T20:17:14
| Not valid after:  2024-06-05T20:17:13
| MD5:   4d3f:dbb9:09af:5822:120f:6dd6:1e16:9544
|_SHA-1: d403:fad0:1e66:17aa:d0a6:eb9f:21c8:63f3:aae5:5f2b

Nmap done: 1 IP address (1 host up) scanned in 0.34 seconds

I can follow the DOCS but everything shows me 404 error, some advises?
Thanks!

**Comment by llamafilm** [comment]
I’ve never used Argo tunnel but it sounds like you have made the tunnel point to the Home Assistant port 8123? I believe the Tesla tunnel needs to point to 443 instead.

**Comment by baylanger** [comment]
> When starts on logs says: " nginx: [warn] conflicting server name "tesla,example.es" on 0.0.0.0:443, ignored "
>
There is a coma in that error message. Just to make sure, you are not using "tesla.example.es" for your real fqdn?

I also use Argo tunnel, the tunnel config should point Nginx SSL on port 443.

**Comment by jorgeal94** [comment]
> > When starts on logs says: " nginx: [warn] conflicting server name "tesla,example.es" on 0.0.0.0:443, ignored "
> 
> There is a coma in that error message. Just to make sure, you are not using "tesla.example.es" for your real fqdn?
> 
> I also use Argo tunnel, the tunnel config should point Nginx SSL on port 443.

that's mistake on deleting the original URL for the example, sorry

**Comment by jorgeal94** [comment]
changing port to 443 un cloudflare tunnel (http://192.168.0.2:443)  got the error: 
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx

when trying to go to .well-known/appspecific/com.tesla.3p.public-key.pem

the warning : nginx: [warn] conflicting server name "teslam3.rmxtech.es" on 0.0.0.0:443, ignored
is showing also...  

Some ideas? Thanks so much!

**Comment by baylanger** [comment]
It should be https and you might need to put the actual FQDN and not the IP address. With https you don't need to specify port 443, it's the default.

**Comment by jorgeal94** [comment]
> It should be https and you might need to put the actual FQDN and not the IP address. With https you don't need to specify port 443, it's the default.

Could you share your config? I´m a bit lost...Made some changes on Nginx and lost the remote and local access...Now I can access again, but dont know how to continue... Thanks fo replying!

**Comment by baylanger** [comment]
I'm not sure how you made changes for Nginx but if you use the add-on, which you should be using, this is my yaml config. I have cloudflare:true but I just realized I don't need it anymore.. instead I use Wireguard to access directly my local network. Depending how you access your HA instance, perhaps you want to keep it, regardless true or not it shouldn't break anything.

```
domain: homeassistant.example.com
hsts: max-age=31536000; includeSubDomains
certfile: fullchain.pem
keyfile: privkey.pem
cloudflare: true
customize:
  active: true
  default: nginx_proxy_default*.conf
  servers: nginx_proxy/*.conf
```

You shouldn't made manual changes in the nginx docker config, unless you know what you're doing.

If your HA configuration.yaml file, below is what you should have for the http: section. No need to define SSL certs or ports.
```
http:
  trusted_proxies:
    - 172.30.33.0/24
  use_x_forwarded_for: true
```

Hope the above helps, otherwise post your config.

**Comment by baylanger** [comment]
The cloudflare argo config that I use:

```
url: https://homeassistant.example.com/
tunnel: 23fef8df-7113-....
credentials-file: /etc/cloudflared/23fef8df-7113-....json
```

At cloudflare, you need : tesla.example.com CNAME that points the dedicated "tesla callback" argo tunnel.

**Comment by baylanger** [comment]
Based on what we discussed above, there doesn't seem to be any issue w/ the add-on. I suggest you close this issue, go in the Discussions area and start a new conversation with a title that matches your environment (cloudflare argo, nginx add-on or nginx external?, HAOS or HA docker? etc).

**Comment by jorgeal94** [comment]
> Based on what we discussed above, there doesn't seem to be any issue w/ the add-on. I suggest you close this issue, go in the Discussions area and start a new conversation with a title that matches your environment (cloudflare argo, nginx add-on or nginx external?, HAOS or HA docker? etc).

Ok, moving to discussions area, thanks for replying!

**Comment by jorgeal94** [comment]
Ok, moving to discussions area, thanks for replying!
