### ISSUE TITLE
Set up http proxy with nabucasa

### ISSUE THREAD

**Issue by Nik18111997** [llamafilm/tesla-http-proxy-addon#24]
Hi, is possible to configure your add on with nabucasa set up ? Thanks a lot

**Comment by baylanger** [comment]
Per say, there's no issue with the add-on. You can reuse the same title to open a Discussion dedicated for Nabu Casa. So many projects don't have Discussions available, it's often everyone goto to open an Issue... Note that I've done that mistake not long ago right here in this project :D 

I don't use Nabu Casa, hopefully others will chip in. Perhaps it's a good question to post on their mailing-list, I would think you're not the only one using NC w/ a Tesla car.

**Comment by Nik18111997** [comment]
Ah sorry, now I open a discussion, thanks
