### ISSUE TITLE
Issues with add-on configuration

### ISSUE THREAD

**Issue by AlexPotterOnGit** [llamafilm/tesla-http-proxy-addon#27]
Hi there,

Trying to get through the setup, not really successfull for now. I do run HA as a VM, NGINX as add-on. external access on 443 port is configured, I can see the content of the key(-----BEGIN PUBLIC KEY-----
bla-bla-bla
-----END PUBLIC KEY-----
but having a browser warning about certificate issue. Is it expected? Certificate still showing my normal domain name. 
Next error (pretty sure related) with Tesla request. i can't get pass Origin URLS - it says Invalid domain, domain must be registered with certificate authority.

Docs says nothing about re-registering certificates for tesla.mydomain.com 
Add-on logs has no errors:
[22:32:28] INFO: Found existing keypair
[22:32:28] NOTICE: Request application access with Tesla, then fill in credentials and restart addon.

![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/82253686/0ffd056c-61b7-4cc1-b2b3-a6ad5a804e1d)

ngix-config:
    server {
        server_name tesla.mydomainheremodified.com;

        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;

        # dhparams file
        ssl_dhparam /data/dhparams.pem;

        listen 443 ssl http2;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

        resolver 127.0.0.11;
        set $target c03d64a7-tesla-http-proxy;
        
        # temporary Flask app for initial auth
        location / {
            proxy_pass http://$target:8099;
        }

        # static public key for Tesla
        location /.well-known/appspecific/com.tesla.3p.public-key.pem {
            root /share/tesla;
            try_files /com.tesla.3p.public-key.pem =404;
        }
    }

Cheers

**Comment by llamafilm** [comment]
You need a valid certificate on both domains.  A wildcard cert is fine.

**Comment by baylanger** [comment]
Do you use Let’s Encrypt add-on to generate the cert? If you have your own domain, request a wildcard cert. if you use something like DynDNS, request a multi domain SAN cert.

Hope this helps.
