### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by danielnitsche** [llamafilm/tesla-http-proxy-addon#4]
Thanks so much for this addon! Just attempted to install / enable, but I get a `502: Bad Gateway` error

```
HAOS on a Raspberry PI 4

Core
2024.2.0

Supervisor
2024.01.1

Operating System
11.5

Frontend
20240207.0
```

When I try and start this addon, I get:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

### Current Nginx configuration ###
{
  "domain": null,
  "hsts": "max-age=31536000; includeSubDomains",
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "cloudflare": false,
  "customize": {
    "active": false,
    "default": "nginx_proxy_default*.conf",
    "servers": "nginx_proxy/*.conf"
  }
}

### Adding custom config to /share/nginx_proxy/nginx_tesla.conf ###
/app/run.sh: line 21: /share/nginx_proxy/nginx_tesla.conf: No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by danielnitsche** [comment]
Ah sorry, just discovered the DOCs.md, will try that and report back: https://github.com/llamafilm/tesla-http-proxy-addon/blob/be81799790be118f5b16af3b6f111333013be7b4/tesla_http_proxy/DOCS.md

**Comment by llamafilm** [comment]
The `tesla_nginx.conf` is hardcoded to work with local development.  I need to fix this to use the correct hostname of this addon.

**Comment by danielnitsche** [comment]
Haven't progressed much with this -- having home assistant accessible via public DNS will take a bit of time for me. I assume you can't turn this off even once the addon is configured?

Re: this issue, I see one of your forks made this change:
https://github.com/llamafilm/tesla-http-proxy-addon/commit/11edd4398571f29682c34cb9fc729e3e63e4dc8f

**Comment by llamafilm** [comment]
That's correct, the public key must remain available on a publicly resolvable FQDN forever.  As I understand, it will be checked by the vehicle to validate each command.

**Comment by llamafilm** [comment]
That's correct.  Both issues are fixed now in the latest version.
