### ISSUE TITLE
Unable to Share Vehicle: This third party isn't registered with Tesla. We can't grant them access at the time.

### ISSUE THREAD

**Issue by e2m32** [llamafilm/tesla-http-proxy-addon#41]
**Describe the bug**
I've followed the instructions trying to set this up. Man, Tesla has really made a lot of hoops for us to jump through now 😢

I set up another domain using duckdns and registering it with the Duck DNS (with Lets Encrypt) addon. Everything seems to be working. I also forwarded port 443 to my home assistant behind my firewall. I am able to reach the server from outside the network (tested on cell connection). With the this addon and nginx running when I go to my https://<tesla-example.duckdns.org> I get the Web UI for this addon with the "Generate OAuth token" and other buttons.

When I click "Generate OAuth token" and authenticate with Tesla, everything seems to work and I get the Tesla Custom component token information in this addon's logs 👍.

Then when I go back to the WebUI and click "Enroll public key in your vehicle", my Tesla app opens as expected and it starts to try to authenticate... then I get a popup that stays: 
`❌Unable to Share Vehicle: This third party isn't registered with Tesla. We can't grant them access at the time.`
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/10486510/90afa9d4-509b-47ab-b296-10588ab18b71)

When I click the "Test public key endpoint", chrome opens on my phone with the "Dangerous site" warning (something wrong with the certificate?). If I bypass the warning (Details > this unsafe site), I just get a blank white page.
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/10486510/ff0b18cf-e33c-48de-a3ca-ab043da42143)

When I restart the addon I get this in the logs:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:52:01] INFO: Found existing keypair
[14:52:01] NOTICE: Starting temporary Python app for authentication flow
[14:52:02] main:INFO: *** Generating Partner Authentication Token ***
[14:52:03] main:INFO: *** Registering Tesla account ***
[14:52:04] main:ERROR: Error 400: Bad Request
[14:52:04] main:INFO: {"response":null,"error":"Invalid EC public key","error_description":""}
[14:52:04] main:INFO: *** Starting Flask server... ***
[14:52:04] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.30.33.13:8099
[14:52:04] werkzeug:INFO: Press CTRL+C to quit
```

Where did I go wrong? Help 🙏

**Environment (please complete the following information):**
 - Home Assistant version: `2024.3.0`
 - Home Assistant install method: [supervised, HAOS, container, etc.] `HAOS 12.0`
 - Addon version: `1.3.2`
 - Region: `US`
 - Vehicle model and year: `2021 Model Y`
 - Your public domain name: using a subdomain of duckdns.org

**Comment by llamafilm** [comment]
It sounds like something is wrong with the TLS cert on your domain.  Please share your real domain name so we can help you debug it.

**Comment by cebertowicz** [comment]
Experiencing the same issue with A+ report from SSL labs

**Comment by llamafilm** [comment]
If you don't share your real domain I can't help you.

**Comment by e2m32** [comment]
I'm nervous publicly posting my domain and home assistant IP address for all to see. 

I did notice that my`com.tesla.3p.public-key.pem` file is empty which might explain the `{"response":null,"error":"Invalid EC public key","error_description":""}` error in the log file.

**Comment by llamafilm** [comment]
Ah, ok it sounds like you hit the same bug as another user.  Delete that file, then update to 1.3.3 and try again.

**Comment by e2m32** [comment]
Ok, cool. Tried it and I am still getting the same "Dangerous Site" error for `https://<REDACTED>.duckdns.org/.well-known/appspecific/com.tesla.3p.public-key.pem` and I get the same error in the Tesla app.

The logs give this error:
```
[03:47:21] main:ERROR: Error 424: Failed Dependency
[03:47:21] main:INFO: {"response":null,"error":"Public key download failed for https://<REDACTED>.duckdns.org/.well-known/appspecific/com.tesla.3p.public-key.pem, error: SSL_connect returned=1 errno=0 peeraddr=<XX.XX.XX.XX>:443 state=error: certificate verify failed (self signed certificate)","error_description":""}
```

Chrome doesn't complain about the SSL cert if I go to `https://<REDACTED>.duckdns.org`... that brings up the AddOn's button page. 🙄

I checked the cert using https://dnschecker.org/ and it all looks correct. The domains align and it's signed by Let's Encrypt... ahh, but I just hit refresh and it's pulling my pfSense self-signed cert... Eh, how do I fix that?

**Comment by ryanelliottsmith** [comment]
I had this issue, it was because the domain I was using for tesla-http-proxy wasn't in the "Allowed Origin's" list in the tesla app

**Comment by llamafilm** [comment]
You should be able to view the public key in a web browser with no errors. If that’s not working, you need to solve that before doing anything else.

**Comment by cnn888** [comment]
Me too have this problem. I have followed all the steps but always stuck at generating oauth. 

![IMG_4203](https://github.com/llamafilm/tesla-http-proxy-addon/assets/8339159/5c5d6d50-55a2-4ef3-b29e-7a14c4382242)

Logging in the oauth link of the webui gives me a blank page saying error cannot open page. 

![Uploading IMG_4204.png…]()

**Comment by llamafilm** [comment]
It sounds like something is wrong with your nginx config. It’s hard to help without knowing how your domain, nameservers, and network are configured.

**Comment by cnn888** [comment]
Ok i will check the nginx and see if this is the culprit. I am using cloudflare tunnel as well if that might be causing it.

**Comment by e2m32** [comment]
I have tried getting this to work for 5 days now 😭 and have spent hours cycling in what feels like infinite loops. Please, please can anyone help before I loose my sanity. 🙏

After trying everything I could think of to get this to work with duckdns domins, I gave up and decided to just purchase a domain. 

## Cloudflare attempt
I got a domain from namecheap and set it up with cloudflare as the dns provider. I then setup the Cloudflare integration in HA to keep my IP address in sync with cloudflare. I set up an `A` type DNS record in cloudflare that points to my network and have port 443 forwarded to HA. I setup the NGINX addon with the new domain and got a SSL cert from cloudflare and put them in the `/ssl` directory and pointed the NGINX at them.

![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/10486510/16e4719f-e75e-4797-938b-1556dbc27ce8)
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/10486510/815c747a-87f6-43b4-a619-3a422191bdce)

The issue is that when I go to my domain externally, it times out. But if I set up NGINX with a duckdns domain, it works like a charm. So my guess is that there is something that cloudflare is doing or not doing where the domain data is not passed on to NGINX and therefore it ignores the request instead of forwarding it on. NGINX doesn't give me any log information if a request fails though. Is there a way to turn that on? Is there some type of setting I am missing in Cloudflare? Am I doomed to just not get this working?

**Things I've tried:**
- Both proxied and "DNS only" with cloudflare (same behavior)
- Pinging my domain resolves my IP correctly
- Tried `NGINX Home Assistant SSL proxy` add-in and `Nginx Proxy Manager` add-in. Same behavior with both.
- Changed the port that pfSense uses for https and turned off HSTS and WebGUI redirect as it seemed to be causing issues.

**Comment by llamafilm** [comment]
@e2m32 your description sounds correct to me.  I really don't understand the hesitation of sharing a public domain name.  Your public IP is probably being port scanned every day by Chinese bots anyway.

curl, netcat, nmap, and dig may be helpful for troubleshooting.

**Comment by ryanelliottsmith** [comment]
@e2m32 what do the logs on the cloudflared process look like? There's something in the config(at least when I last looked at it) that breaks SNI when using a reverse proxy, even if you're passing through headers. I was seeing "name unknown" type  responses from nginx with the tesla-http-proxy config that the app builds.
In the short term, I reconfigured it for http between cloudflare and nginx, when I get some time I'll dig into it.

**Comment by e2m32** [comment]
Hey, thank you for your suggestions! I was able to get my main domain to work with cloudflare when I set the encryption mode to Flexible. I think there was an issue with the SSL cert that I created in Cloudflare and was using with `Nginx Proxy Manager`. I ended up using `Nginx Proxy Manager` to create a LetsEncrypt cert for me (using a DNS Edit API key) and started using that. Now I can use cloudflare's Full encryption mode 🙌

I went back to `NGINX Home Assistant SSL proxy` add-in so I could use it with `tesla-http-proxy-addon` and loaded the new SSL certs, followed the DOCS and was able to authenticate with tesla and my car! 🎉 My domain is now listed under keys in the car's display. So cool.

I restarted the `tesla-http-proxy-addon` , and attempted to link it with `Tesla Custom Integration` and then ran into another hiccup. 😞 After entering the requested info (Refresh token, etc), it fails to authenticate. There is no info in the `tesla-http-proxy-addon` logs. Just the following: 

![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/10486510/0822ef57-66e9-457d-a690-251db4df2df5)

Any advise at this point? It's interesting to me that it's listening on 443... Shouldn't it be listening on 4430? Or is 443 internal to the add on and 4430 is what is exposed external to HA?

**Comment by llamafilm** [comment]
I don't think profile information is required in the scopes.
Port 4430 is not used for anything in a standard HAOS installation.
It sounds like this addon is working properly.  Please enable debug logging from the Tesla integration and share the logs (in a formatted code block).  The most common issue I see is the `login_required` error which means the refresh token has already been used.  If that happens, you'll need to delete the car "device" and add it back.

By the way, there is no reason to redact a public key.  It is by nature, public.

**Comment by e2m32** [comment]
Got it! I removed the Tesla Custom integration and went through the entire process again, and now it is working! Thank you so much! 
🚗♥🏠 again! :)

**Comment by chowdarygm** [comment]
I am having similar issues as the first post in this. This third party isn't registered with Tesla. We can't grant them access at the time. I am using the cloudflare process mentioned in this [blog ](https://www.smartmotion.life/2024/04/06/tesla-integration-with-home-assistant/?v=6cc98ba2045f). Setup two times but still end up with this issue and unable to figure out what's wrong.  Able to access public key just fine.

my domain name is https://tesla.chowdaryonline.org 

Appreciate any help on this

This is the log from Tesla Proxy addon

```
[19:00:31] werkzeug:INFO: 172.30.32.2 - - [15/Apr/2024 19:00:31] "GET / HTTP/1.1" 200 -
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:21052: EOF
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:25722: EOF
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:29344: EOF
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:34018: tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq])
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:37348: tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9])
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:41182: EOF
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:45012: tls: peer doesn't support any of the certificate's signature algorithms
2024/04/15 19:11:03 http: TLS handshake error from 212.102.40.218:49016: EOF
2024/04/15 19:11:04 http: TLS handshake error from 212.102.40.218:52962: EOF
2024/04/15 19:11:04 http: TLS handshake error from 212.102.40.218:57402: tls: peer doesn't support any of the certificate's signature algorithms
2024-04-15T19:18:38-05:00 [info ] Received GET request for /
2024-04-15T19:18:38-05:00 [error] Returning error Forbidden
2024/04/15 19:23:23 http: TLS handshake error from 206.168.34.184:57784: EOF
2024/04/15 19:23:24 http: TLS handshake error from 206.168.34.184:56518: EOF
2024/04/15 19:23:24 http: TLS handshake error from 206.168.34.184:48454: EOF
2024/04/15 19:23:24 http: TLS handshake error from 206.168.34.184:52142: tls: client requested unsupported application protocols ([http/0.9 http/1.0 spdy/1 spdy/2 spdy/3 h2c hq])
2024/04/15 19:23:24 http: TLS handshake error from 206.168.34.184:60824: tls: client requested unsupported application protocols ([hq h2c spdy/3 spdy/2 spdy/1 http/1.0 http/0.9])
2024/04/15 19:23:25 http: TLS handshake error from 206.168.34.184:36136: EOF
2024/04/15 19:23:25 http: TLS handshake error from 206.168.34.184:57922: tls: peer doesn't support any of the certificate's signature algorithms
2024/04/15 19:23:26 http: TLS handshake error from 206.168.34.184:58816: EOF
2024/04/15 19:23:26 http: TLS handshake error from 206.168.34.184:56586: EOF
2024/04/15 19:23:26 http: TLS handshake error from 206.168.34.184:34584: tls: peer doesn't support any of the certificate's signature algorithms
2024/04/15 19:33:35 http: TLS handshake error from 192.155.90.220:16750: EOF
``` 

This is the log from Apache addon

```
172.30.32.1 - - [15/Apr/2024:19:53:33 -0500] "GET /apple-touch-icon.png HTTP/1.1" 403 287
172.30.32.1 - - [15/Apr/2024:19:53:33 -0500] "GET /apple-touch-icon-precomposed.png HTTP/1.1" 403 287
[Mon Apr 15 19:53:33.825383 2024] [authz_core:error] [pid 141] [client 172.30.32.1:39318] AH01630: client denied by server configuration: /share/tesla/apple-touch-icon-precomposed.png
[Mon Apr 15 19:53:33.839442 2024] [authz_core:error] [pid 141] [client 172.30.32.1:39318] AH01630: client denied by server configuration: /share/tesla/
172.30.32.1 - - [15/Apr/2024:19:53:33 -0500] "GET / HTTP/1.1" 403 287
[Mon Apr 15 19:53:33.940334 2024] [authz_core:error] [pid 141] [client 172.30.32.1:39318] AH01630: client denied by server configuration: /share/tesla/apple-touch-icon.png
172.30.32.1 - - [15/Apr/2024:19:53:33 -0500] "GET /apple-touch-icon.png HTTP/1.1" 403 287
172.30.32.1 - - [15/Apr/2024:19:53:33 -0500] "GET /favicon.ico HTTP/1.1" 403 287
[Mon Apr 15 19:53:33.978544 2024] [authz_core:error] [pid 141] [client 172.30.32.1:39318] AH01630: client denied by server configuration: /share/tesla/favicon.ico
[Mon Apr 15 19:53:34.047185 2024] [authz_core:error] [pid 141] [client 172.30.32.1:39318] AH01630: client denied by server configuration: /share/tesla/favicon.ico
172.30.32.1 - - [15/Apr/2024:19:53:34 -0500] "GET /favicon.ico HTTP/1.1" 403 287
[Mon Apr 15 20:17:49.689859 2024] [authz_core:error] [pid 139] [client 172.30.32.1:44928] AH01630: client denied by server configuration: /share/tesla/
172.30.32.1 - - [15/Apr/2024:20:17:49 -0500] "GET / HTTP/1.1" 403 287
[Mon Apr 15 20:17:49.786110 2024] [authz_core:error] [pid 139] [client 172.30.32.1:44928] AH01630: client denied by server configuration: /share/tesla/favicon.ico, referer: https://tesla.chowdaryonline.org/
172.30.32.1 - - [15/Apr/2024:20:17:49 -0500] "GET /favicon.ico HTTP/1.1" 403 287
172.30.32.1 - - [15/Apr/2024:20:19:19 -0500] "GET /.well-known/appspecific/com.tesla.3p.public-key.pem HTTP/1.1" 200 178
172.30.32.1 - - [15/Apr/2024:20:19:19 -0500] "GET /favicon.ico HTTP/1.1" 403 287
[Mon Apr 15 20:19:19.706905 2024] [authz_core:error] [pid 140] [client 172.30.32.1:37978] AH01630: client denied by server configuration: /share/tesla/favicon.ico, referer: https://tesla.chowdaryonline.org/.well-known/appspecific/com.tesla.3p.public-key.pem
172.30.32.1 - - [15/Apr/2024:20:19:40 -0500] "GET /.well-known/appspecific/com.tesla.3p.public-key.pem HTTP/1.1" 206 178
172.30.32.1 - - [15/Apr/2024:20:33:19 -0500] "GET /.well-known/appspecific/com.tesla.3p.public-key.pem HTTP/1.1" 304 -
[Mon Apr 15 20:33:20.075786 2024] [authz_core:error] [pid 145] [client 172.30.32.1:48036] AH01630: client denied by server configuration: /share/tesla/favicon.ico, referer: https://tesla.chowdaryonline.org/.well-known/appspecific/com.tesla.3p.public-key.pem
172.30.32.1 - - [15/Apr/2024:20:33:20 -0500] "GET /favicon.ico HTTP/1.1" 403 287
```
