### ISSUE TITLE
/app/run.sh: line 42: /root/go/bin/tesla-keygen: No such file or directory

### ISSUE THREAD

**Issue by olyashok** [llamafilm/tesla-http-proxy-addon#42]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[22:49:19] INFO: Current Nginx configuration
{"domain":"xaser.duckdns.org","hsts":"max-age=31536000; includeSubDomains","certfile":"fullchain.pem","keyfile":"privkey.pem","cloudflare":false,"customize":{"active":true,"default":"nginx_proxy_default*.conf","servers":"nginx_proxy/*.conf"}}
[22:49:19] INFO: Adding custom config to /share/nginx_proxy/nginx_tesla.conf
    server {
        server_name XXXXXXXXXXX;
        ssl_certificate /ssl/fullchain.pem;
        ssl_certificate_key /ssl/privkey.pem;
        # dhparams file
        ssl_dhparam /data/dhparams.pem;
        listen 443 ssl http2;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        resolver 127.0.0.11;
        set $target c03d64a7-tesla-http-proxy;
        
        # temporary Flask app for initial auth
        location / {
            proxy_pass http://$target:8099;
        }
        # static public key for Tesla
        location /.well-known/appspecific/com.tesla.3p.public-key.pem {
            root /share/tesla;
            try_files /com.tesla.3p.public-key.pem =404;
        }
    }
[22:49:19] INFO: Generating self-signed SSL certificate
-----
[22:49:19] INFO: Generating keypair
/app/run.sh: line 42: /root/go/bin/tesla-keygen: No such file or directory
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by llamafilm** [comment]
Oops, sorry about that! I broke it in the last update. I will fix it tonight.

**Comment by llamafilm** [comment]
Fixed in v1.3.3
