### ISSUE TITLE
Clarify Telsa "Application Access Request" process

### ISSUE THREAD

**Issue by danielnitsche** [llamafilm/tesla-http-proxy-addon#5]
Few suggestions on how to improve documentation. Happy to help with a PR, just need to clarify some things.

- Application Name / Application Usage / Purpose of Usage -- should we suggest what users should enter? Or will they work it out themselves.
- OAuth grant type -- should users choose `Authorization Code and Machine-to-Machine`, or `Machine-to-Machine only`
- What `API & Scopes` are necessary?
- Does the app need to be approved before it can be used? It says 4-5 days I think, but mine was approved in a couple of hours

**Comment by danielnitsche** [comment]
As per other issue, just discovered DOCS.MD: https://github.com/llamafilm/tesla-http-proxy-addon/blob/be81799790be118f5b16af3b6f111333013be7b4/tesla_http_proxy/DOCS.md

**Comment by llamafilm** [comment]
Good point, one thing I forgot to mention is you need to request **Authorization Code and Machine-to-Machine**
