### ISSUE TITLE
Unable to start addon after initial configuration

### ISSUE THREAD

**Issue by Diondk** [llamafilm/tesla-http-proxy-addon#50]
**Describe the bug**
i put in all configuration and everything is downloaded public key is generated.
But when i click open webgui the webpage gives an 502 and the addon provides a error in the log

I am running HAOS with a remote NGINX running in docker not on HAOS itself. 

I have forwared port 4430 and 8099 to HAOS 

**To Reproduce**
1. Go to 'addon'
2. Click on 'start'
3. Click on logs

**Expected behavior**
Addon should start

**Screenshots**

**Environment (please complete the following information):**
 - Home Assistant version: 2024.3.1
 - Home Assistant install method: HAOS
 - Addon version: 1.3.4
 - Region: Europe
 - Vehicle model and year: Tesla Model 3 2019
 - Your public domain name.: xxx

**Logs**
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[14:27:13] INFO: Found existing keypair
[14:27:13] INFO: Testing public key...
HTTP/2 502 
server: openresty
date: Mon, 18 Mar 2024 13:27:14 GMT
content-type: text/html
content-length: 154

[14:27:14] ERROR: Fix public key before proceeding.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Additional context**

**Comment by Diondk** [comment]
Fixed it after making some changes in location of the certificate on nginx proxy manager

**Comment by MicheleMercuri** [comment]
I tried to use Nginx Proxy Manager but with no success (I use a reverse proxy with DuckDNS and port 443 to access my server from outside my home). Can you share your Nginx proxy manager settings? tnks.

**Comment by Diondk** [comment]
Its not that simple of sharing the configuration its a bit of manual work, i will do my best to describe the work. 

First you need to create an additional proxy in nginx pointing to port 4430, please make sure there is an valid SSL certificate added to this new proxy host.

Then you need to copy the com.tesla.3p.public-key.pem file to your nginx proxy manager at /data/tesla/
Add the following under advanced in your proxy you just created
`location = /.well-known/appspecific/com.tesla.3p.public-key.pem {
    alias /data/tesla/com.tesla.3p.public-key.pem;
}`

Under Custom Locations create a location /callback 
point it to port 8099 on the HA server. 

Now run the proxy in Home Assistant and check the log files if its able to see the pem file. If that is the case you can follow the documentation again.

**Comment by MicheleMercuri** [comment]
Many thanks for your help, but it seems my configuration might have some mistakes. After I started the 'Tesla HTTP proxy', when I try to generate keys, I receive a '502 Bad Gateway' error page along with these logs (the keypair had been generated in a previous test)
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:32:06] INFO: Found existing keypair
[18:32:06] INFO: Testing public key...
HTTP/2 404 
server: nginx
date: Thu, 21 Mar 2024 17:32:06 GMT
content-type: text/html
content-length: 146
strict-transport-security: max-age=63072000;includeSubDomains; preload

[18:32:06] ERROR: Fix public key before proceeding.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

and this is NGINX configuration:
![1](https://github.com/llamafilm/tesla-http-proxy-addon/assets/97225788/9bf9b5d8-5cff-4e4f-9baa-2b8cbe9e715a)
![2](https://github.com/llamafilm/tesla-http-proxy-addon/assets/97225788/4ce126fb-1243-4c1f-84ef-1ab299cf9ffe)
![3](https://github.com/llamafilm/tesla-http-proxy-addon/assets/97225788/2ad5b249-62cc-44dc-935f-2ea703795bf0)
![4](https://github.com/llamafilm/tesla-http-proxy-addon/assets/97225788/a6addec4-090d-4acb-b033-bf9d772c4f16)

**Comment by Diondk** [comment]
Can you try to add another location usign the following info?
![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/4394449/d3756350-454e-4cea-94fa-018b2700ff53)

Afterthat try to browse to your_model_3.duckdns.org/.well-known/appspecific/com.tesla.3p.public-key.pem
And see if the key is being downloaded if that works it means tesla will be able to reach the key also and you can try it again.

Please make sure you have registered your app with tesla on the NEW url you created. Do not try to get this working with the existing home assistant duckdns you already have. Because i wasnt able to get that to work either.

**Comment by MicheleMercuri** [comment]
still "502: Bad Gateway" I running Nginx in HAOS, key in \share\tesla and are ok but I can't download it.

**Comment by Diondk** [comment]
But if your running nginx in HAOS you need to follow the normal steps and not the steps i did. I am running nginx on a different host and not on my HAOS
