### ISSUE TITLE
Log error after succesfull install 

### ISSUE THREAD

**Issue by Arylolha** [llamafilm/tesla-http-proxy-addon#53]
**Describe the bug**
First thank you for your amazing job, after some hours I finally arrive to make it work, I can now send command to the car!
I have very low computer skills so I made the installation several times to make it work without understanding everything.
I notice that despite the fact it's running and working I have a lot of erros:

- When I try to open in add on web interface:  Home assistant say: Tesla http proxy  - The add on seems to not be ready it could be in lauching now  (bad translation from my native langage :s ) Is it normal?
In the log it's spaming (2 times per minute) 
2024-03-19T20:55:38+01:00 [info ] Received GET request for /api/1/products
2024-03-19T20:55:38+01:00 [debug] Forwarding request to https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/products

NGINX: in the log even if I don't launch anything I have a lot of 
024/03/19 20:32:04 [error] 149#149: *2856 connect() failed (111: Connection refused) while connecting to upstream, client: 89.104.101.251, server: _tesla-example.duckdns.org_, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.30.33.6:8099/favicon.ico", host: "tesla-example.duckdns.org"

or

2024/03/19 13:07:21 [error] 149#149: *2814 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.254, server: tesla-example.duckdns.org, request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.30.33.6:8099/favicon.ico", host: "tesla-example.duckdns.org", referrer: "https://tesla-example.duckdns.org/callback?locale=en-US&code=EU_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&issuer=https%3A%2F%2Fauth.tesla.com%2Foauth2%2Fv3"

It happen randmly while there not automation or me using sending command

**Environment (please complete the following information):**
 - Home Assistant version: 2024.3.1
 - Home Assistant install method: HAOS on proxmox pc
 - Addon version: 1.3.4
 - Region: europe 
 - Vehicle model and year MODEL Y 2023

THank you again !

**Comment by llamafilm** [comment]
Your computer skills must be decent if you were able to install this properly, it’s not easy!

The web UI is only meant to be used for initial authentication. After that it will show an error, that’s normal.

The log messages are also normal. Maybe later I will start hiding those, but since this whole thing is experimental I think it’s best to show everything for now.

The favicon error is harmless. There’s probably some way to stop it with nginx config, and if you figure that out, please contribute a PR.

**Comment by llamafilm** [comment]
I've just pushed a change for this, try updating your nginx config like this: c0888f3

**Comment by Arylolha** [comment]
Thank you i'll try it tonight.

Happy to Know that these errors are no big deal.

I'm so happy to have full acces again to my tesla. I can setup my solar energy automation. I was thinking in the begining that sending command through all this Will be à little bit laggy but it's not, it's very fast. 

The journey to make it work maybe painfull but it's worth it.

**Comment by llamafilm** [comment]
/share/nginx_proxy/nginx_tesla.conf

**Comment by Arylolha** [comment]
Thank you I have change the file and update to 1.3.6 the nginx log looks good so far!

**Comment by Arylolha** [comment]
I notice a bug I didn't have before 1.3.6.

If I launch sentry mode on the car than I stop it both with HA it's working find but if i lauch sentry mode with HA and stop it directly in Tesla App the tesla integration stay on Sentry mode "On".

If I connect to tesla integration page sentry mode off and I launch it with tesla app on the integration page it's also not changing.

It tried with charger door and it's the same thing. Not sure it's related to tesla http proxy or the integration itself but pretty sure that before 1.3.6 it was working.

**Comment by llamafilm** [comment]
I doubt this is related to the proxy.  It might be an issue with the integration, or you might just need to wait a while for it to update.

**Comment by jesperholstjh** [comment]
@llamafilm I'm curious about the 
`2024-05-29T15:49:50+02:00 [info ] Received GET request for /api/1/products
2024-05-29T15:49:50+02:00 [debug] Forwarding request to https://fleet-api.prd.eu.vn.cloud.tesla.com/api/1/products`

Which seems to get logged every minute. I get that they're expected, i'm just curious on why that is? What purporse do they serve, and why is it needed? 

I'm trying to debug a `Server returned 429: Too Many Requests: Retry later` error and a not sleeping car, but i presume that just my config. Not sure what the rate limit is at the API.

But while debugging the above, I ran into the 'products' log-line. I can see it's related to https://developer.tesla.com/docs/fleet-api#products - but why is it sent every minute?


Also, thanks for making this possible. You're genuinely awesome!

**Comment by llamafilm** [comment]
That doesn’t come from my code. I believe it’s from the Tesla Home Assistant integration. The products endpoints returns a a list of vehicles with VIN number and sleep status, which it uses to decide whether or not to poll the vehicle. Unlike all the other endpoints, this one does not hit the vehicle, and I _think_ the rate limit are higher. 

If you find any solution to the 429 error I’ll be glad to hear about it! I’m not using this anymore because of that. My main purpose was adjusting the charge rate to match excess solar output.
Unless Tesla announces a higher rate tier, I think the only solution is to switch to BLE.

**Comment by andreaconfa** [comment]
Hi, i need this integration for the same reason and i ran into the same problem: Error 429

Do you think that is possible to make home assistant talk to the car via BLE?
