### ISSUE TITLE
1.3.5 cant install tesla-http-proxy-addon

### ISSUE THREAD

**Issue by speeli** [llamafilm/tesla-http-proxy-addon#55]
i removed this addon because had a issue with updating to 1.3.5.
after removing i cant install it again.

error code:
`
Can't install ghcr.io/llamafilm/tesla_http_proxy_amd64:1.3.5: 500 Server Error for http+docker://localhost/v1.43/images/create?tag=1.3.5&fromImage=ghcr.io%2Fllamafilm%2Ftesla_http_proxy_amd64&platform=linux%2Famd64: Internal Server Error ("manifest unknown")`

**Comment by llamafilm** [comment]
This seems to be a bug in GitHub Actions, my last build keeps failing. In the meantime you can use the previous version.

**Comment by thiagobruch** [comment]
I'm having the same issue to install the addon on Home Assistant.

**Comment by alexeiw123** [comment]
> This seems to be a bug in GitHub Actions, my last build keeps failing. In the meantime you can use the previous version.

How can I get a previous version through HA Add-ons?

**Comment by llamafilm** [comment]
I don't think you can do it through the UI.  You'd have to download the ZIP from GitHub and copy the tesla_http_proxy folder into `/addons`.

**Comment by alexeiw123** [comment]
> I don't think you can do it through the UI. You'd have to download the ZIP from GitHub and copy the tesla_http_proxy folder into `/addons`.

I only see a v1.3.0 unless I'm missing something? https://github.com/llamafilm/tesla-http-proxy-addon/releases/tag/v1.3.0
Because I'd installed it previously I just restored a HA backup of the add-on only, so at least now I have v1.3.3

**Comment by llamafilm** [comment]
Oh, good point.  I haven't been making tags on this repo.  I'm glad the backup/restore solved it for you.

**Comment by speeli** [comment]
for me its fixed with 1.3.6, so we can close this issue.

Thanks llamafilm for you fast response and help :)
