### ISSUE TITLE
Remove requirement for Nginx SSL proxy

### ISSUE THREAD

**Issue by Zarklord** [llamafilm/tesla-http-proxy-addon#6]
I don't run a proxy per service, instead I have one singular reverse proxy, for all my services (it's also not hosted on home assistant, and I have no desire to have it hosted there)

Because of this, this add on in it's current state is unusable for me, looking it over, I need the ability to forward both the flask port 8099, and the tesla-http-proxy (from port 443 to a custom port), that I then use my reverse proxy to control traffic to those ports.

Additionally, I believe the `com.tesla.3p.public-key.pem` would need to get moved from /share/tesla to something like /config/www/tesla so that you can proxy to it, from an external service, since the /share directory is not reachable via http requests.

I obviously could maintain my own version, but that has the downside of no one else being able to use it (because I don't have the time to provide support for other users), and also means I'm constantly gonna have to monitor this repository to get improvements from other people for it.

**Comment by llamafilm** [comment]
You can copy the public key wherever you want. 

I think the only thing blocking you is that port 8099 is only open to the internal Docker network. Is that correct? I could open that port to anywhere but then it would lose a point on Home Assistant’s security rating. Can you try and let me know if that solves your problem?

**Comment by Zarklord** [comment]
> I could open that port to anywhere but then it would lose a point on Home Assistant’s security rating.
I gotta be honest, this is why I never pay attention to that number, right now you are "exposing" port 8099 via nginx's ssl proxy.
Exposing the port directly isn't any safer than exposing it from the proxy, yet HASS gives you a point for making the addon less customizable.

You would also need to expose port 443 so that you can actually proxy stuff to the API.
but also if you try and run this addon without the SSL proxy, it will always crash and never startup.

**Comment by llamafilm** [comment]
From where are you trying to send commands to the proxy?  My plan was to make the proxy available _only_ from Home Assistant, so there would be no reason to expose that port.  I'm curious if you have a different use case.

Anyway, I've exposed these ports and put the nginx specific parts behind a condition that only runs if nginx is installed.  See if it works for you now?

If you're planning to expose 443 publicly, take note of this warning from Tesla:
> Do not listen on a network interface without adding client authentication. Unauthorized clients may
be used to create excessive traffic from your IP address to Tesla's servers, which Tesla may respond
to by rate limiting or blocking your connections.

**Comment by Zarklord** [comment]
I'm still sending them only from home assistant, but if I route them through my proxy, I don't have to deal with a custom certificate, since it will just work with my existing wildcard cert.

**Comment by Snuffy2** [comment]
I'd agree. To set this up, I'd put this through my existing reverse proxy with existing SSL wildcard cert. 

I can handle tesla-http_proxy as a HA addon, but I'd prefer to put the proxy on my docker reverse-proxy stack on a different machine and then point the HA tesla_custom (or whatever other tesla integration) there.

**Comment by llamafilm** [comment]
This request doesn’t make sense to me. If you are only hitting the proxy from Home Assistant, then there is no reason to give it a FQDN with wildcard cert.

I understand the desire to use your own proxy for external traffic, but that is only required for the static public key and the temporary auth flow, which should be working today.

**Comment by llamafilm** [comment]
I drew a simplified version of Tesla's new authentication flow.  The red lines show the parts that require SSL proxy to Home Assistant, and the blue line is using the internal self-signed certificate.  I hope it makes sense.

<img width="863" alt="image" src="https://github.com/llamafilm/tesla-http-proxy-addon/assets/3991046/41407444-5916-4405-ad19-2dbe78fe769d">

**Comment by iainbullock** [comment]
I have created a docker version of this project, which means you don't need to install a Home Assistant add-on. This might be useful for those who can't or won't install HA add-ons (e.g. if you are running the docker version of HA).

It's still in Beta, but it does work in so far as registering all the keypairs, installing the key into your vehicle, and use of curl to send commands to the vehicle. I am waiting for the current PR to integrate llamafilm's proxy into Home Assistant, after which I'll make whatever updates are needed to my project to work with HA. 

Great work by llamafilm who has done all the clever stuff!

Check out my project here: https://github.com/iainbullock/tesla-http-proxy-docker/tree/main

**Comment by mercurimichele** [comment]
Hello, I already have a "NGINX proxy manager" setup for Home Assistant with DuckDNS +SSL, and so to be able to also use this integration, I cannot install the "NGINX Home Assistant SSL proxy". How can I integrate the configuration of NGINX proxy manager? tnks

**Comment by llamafilm** [comment]
@iainbullock Do you think you could make a PR against my Dockerfile that will make it work in your environment, without breaking compatibility as an addon?

**Comment by iainbullock** [comment]
> @iainbullock Do you think you could make a PR against my Dockerfile that will make it work in your environment, without breaking compatibility as an addon?

I will attempt to do this, as it would be best if your version could support both approaches. I will have to do some work though to make it compatible with both (and might need some help in doing so).

**Comment by iainbullock** [comment]
@llamafilm Just to continue an excerpt of the conversation from https://github.com/alandtse/tesla/issues/899 (which I've now closed):

My question: The URL to my proxy is https://192.168.1.5:4430/ could you confirm this is the correct format to enter in the Proxy URL box in the config flow?

Your answer: The IP address won't work; it needs to be a domain name which matches the TLS cert.

I created the TLS cert in the first place using the IP address rather than a domain name, and the proxy works when using curl and this cert, e.g.:

curl --cacert selfsigned.pem \
    --header 'Content-Type: application/json' \
    --header "Authorization: Bearer $TESLA_AUTH_TOKEN" \
    --data '{"which_trunk": "rear"}' \
    "https://192.168.1.5:4430/api/1/vehicles/$VIN/command/actuate_trunk"

Works as expected

**Comment by llamafilm** [comment]
Oh I see!  I didn't realize that was possible, but if curl is not complaining then I guess the IP is fine.

Does that curl command work from inside the Home Assistant container?  You may need to connect both containers to the same docker network.

**Comment by iainbullock** [comment]
> Oh I see! I didn't realize that was possible, but if curl is not complaining then I guess the IP is fine.
> 
> Does that curl command work from inside the Home Assistant container? You may need to connect both containers to the same docker network.

Update: I confirm that I can successfully connect from the HA container command line using curl to my proxy.

However:
1 - I've been a complete numpty and have been using the Owners API Refresh Key rather than the Fleet API Refersh Key as generated by the iOS app 'Auth for Tesla'
2 - Now I'm using the correct Refresh Key, the config flow still fails but for different reasons. It does at least now successfully refresh oauth
3 - The reason it is failing now appears to be it not liking my SSL Cert. Even though my SSL Cert (based on IP address not hostname) works for curl, it seems the integration doesn't like it. I won't paste the whole debug log here, but below is the line which gives the clue. Your assertion that a hostname name rather than IP must be specified may well be correct.

File "/usr/local/lib/python3.12/ssl.py", line 917, in do_handshake
  self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.168.1.5'. (_ssl.c:1000)

I will regenerate the SSL key based on hostname when I get time later. I will report back, but I'm feeling confident now. Thanks for the pointer

**Comment by iainbullock** [comment]
OK. I regenerated the SSL keys based on hostname. Same issue. 

I can connect via curl from the HA container, but the python connection from the integration doesn't like it. Logs below.

I also get this error in the proxy log:
2024/03/14 18:43:17 http: TLS handshake error from 172.17.0.1:40246: EOF

I'll do a bit more digging, I can't be far off (no need to respond I can see you've got lots of questions from other people). It doesn't like the SSL key or some other aspect of the connection to the proxy. Any ideas welcome of course, thanks

------

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tesla_custom/__init__.py", line 187, in async_setup_entry
    result = await controller.connect(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 219, in connect
    self._product_list = await self.get_product_list()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 313, in get_product_list
    return (await self.api("PRODUCT_LIST"))["response"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1375, in api
    return await self.__post_with_retries_except_unavailable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/controller.py", line 1407, in __post_with_retries_except_unavailable
    return await self.__connection.post(command, method=method, data=data, url=url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 166, in post
    return await self.__open(url, method=method, headers=self.head, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/teslajsonpy/connection.py", line 207, in __open
    resp: httpx.Response = await getattr(self.websession, method)(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 154, in _connect
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 78, in start_tls
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/streams/tls.py", line 125, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/usr/local/lib/python3.12/site-packages/anyio/streams/tls.py", line 133, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)

**Comment by iainbullock** [comment]
Update, it is now working correctly. 

The issue was with the SSL cert. I found that the SSL cert must:
- Be a hostname not an IP address
- Resolve to the same IP (the docker host IP) in both the HA container (if using docker version of HA) and my proxy container. This required me to set a hostname to IP mapping in my router DNS 

I can now confirm that my version of the proxy (in a docker contianer rather than HA add-on) does work, and HA now has the required functionality with my car (M3 2024 UK model) https://github.com/iainbullock/tesla-http-proxy-docker

I will work on tidying it up, and eventually hope to merge into llamafilm's project so both HA addon and docker versions are supported in the same project 

@llamafilm I appreciate what you have created here and the continung support you are provding to the community 👍

**Comment by loki666** [comment]
I have a different setup, and I'm not sure what to do
my setup is inet -> router -> linux box with traefik reverse proxy docker container -> HAOS on a rpi3
traefik is handling the SSL cert for my home assistant as well as the traffic forwarding for myhomeassistant.mydomain.com

with that setup I don't have the Nginx SSL proxy add-on installed on HAOS

I can easily add a new domain (tesla.mydomain.com) that also forward to my homeassisant IP, but I'm not sure (don't understand) if that's enough ?

**Comment by llamafilm** [comment]
@loki666 actually it’s the other way around. The add on will generate its own self-signed cert which goes in the /share folder so that HA can use it. 
If you read through all the discussions, it sounds like some folks have been able to set this up without Nginx. I don’t have time to validate each unique config, but I suggest people start using the wiki feature here on GitHub to document these different scenarios.

**Comment by loki666** [comment]
ok so if I understand correctly the setup

the flask application on port 8089 is needed for the auth negotation, if exposed on the HAOS eth iface, I can route my reverse proxy to that using tesla.mydomain.com (with a new SSL cert used for the https connection)

the only thing missing will be the access to `com.tesla.3p.public-key.pem` since currently it's being exposed using the Nginx SSL porxy add-on, so if you could make the flask app expose that file also (instead of using nginx) everything should be fine

**Comment by dannytsang** [comment]
Can you also specify the path of the certificate in Traefik as well? The docs says it should in `.well-known/appspecific/com.tesla.3p.public-key.pem` so **https://tesla.example.com/.well-known/appspecific/com.tesla.3p.public-key.pem**

**Comment by loki666** [comment]
no, I set up a nginx docker container with a config close to what this add-on has

```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    server {
        listen     80;
        server_name tesla.mydomain.duckdns.org;

        location / {
            proxy_pass http://192.168.1.41:8099;
        }

        location /.well-known/appspecific/com.tesla.3p.public-key.pem {
            root   /usr/share/nginx/html;
            try_files /com.tesla.3p.public-key.pem =404;
        }
    }
}
```

I created the `com.tesla.3p.public-key.pem` file with what the addons logs
the other location in the config is my rpi3 IP running homeassistant with this add-on

this is my docker create command
`docker create --log-opt max-size=10m --name tesla-proxy -v /var/docker/appdata/tesla-proxy/html:/usr/share/nginx/html:ro -v /var/docker/appdata/tesla-proxy/nginx.conf:/etc/nginx/nginx.conf:ro --network="web" --label traefik.enable=true --label traefik.http.services.tesla.loadbalancer.server.port=80  --label traefik.http.routers.tesla.rule="Host(\`tesla.mydomain.duckdns.org\`)" --label traefik.docker.network=web nginx`

depending your docker setup you may need to change or remove the "web" network arguments

**Comment by abreingan** [comment]
Hi all, 
Wondering where best to post this question, so apologies if this is the wrong spot. 
I am behind a CGNAT isp (starlink) and I assume that would stop me running this proxy.
I do have an external domain name on a Cpanel shared host but I don't think this has enough access to run a docker container or similar with the original Tesla proxy or one of the other variants. I am guessing I would need to go to something like a droplet?
Has anyone gone down this path? Any suggestions?
Thanks in advance

**Comment by llamafilm** [comment]
For testing the Tesla integration in a devcontainer, I needed a way to run this addon standalone, without HAOS.  So I've added a script for this purpose in 4b31c1dc937d28006847c4cbee086bfaa9abdfae.  It mimics some of the HAOS concepts so that the same Docker image will work, and runs a separate Nginx container.  It might be helpful to some of you.
