### ISSUE TITLE
Unable to Onbeard?

### ISSUE THREAD

**Issue by 2Fast2BCn** [llamafilm/tesla-http-proxy-addon#67]
### The problem

![image](https://github.com/llamafilm/tesla-http-proxy-addon/assets/4680358/f441822f-543d-4a8b-ba02-5fba263754f9)

### What version of the addon are you using?

2.1.1

### What version of Home Assistant Core are you using?

2024.3.3

### What type of installation are you running?

Home Assistant OS

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

NA

### What is your domain name (FQDN)?

tesla.allnice.eu

**Comment by 2Fast2BCn** [comment]
Anybody ever seen this?

**Comment by 2Fast2BCn** [comment]
https://github.com/teslamotors/vehicle-command/issues/13

**Comment by llamafilm** [comment]
For this error, I suggest you open a new issue against vehicle-command and include the full text of the error shown in chrome JavaScript console. (Not a screenshot)
