### ISSUE TITLE
Not able to add virtual key

### ISSUE THREAD

**Issue by janchrillesen** [llamafilm/tesla-http-proxy-addon#7]
Hi,
I am trying to install your addon and have gotten to the point where I need to add the virtual key. I get an error from the tesla app (in danish), which can roughly be translated to "Failed to add car. Third party is not registered at tesla". Being in the EU I think it might be related to using the wrong endpoints. There's 3 different, depending on where you are in the world

    "na": "https://fleet-api.prd.na.vn.cloud.tesla.com",
    "eu": "https://fleet-api.prd.eu.vn.cloud.tesla.com",
    "cn": "https://fleet-api.prd.cn.vn.cloud.tesla.cn",

The code currently seems to be hardcoded to use the first one. Would it possible to add a config option to choose the correct region?

**Comment by llamafilm** [comment]
I’ve added this option in v1.2.2. Let me know if it works.

**Comment by janchrillesen** [comment]
I managed to add the virtual key now. I think we can consider this issue solved. However, when trying to issue a call towards the API I get {"error":"token expired (401)"} - is there a way to switch back to the Flask application, without reinstalling the addon?

**Comment by llamafilm** [comment]
Yes - turn on the “regenerate key pair” config setting and restart.

**Comment by janchrillesen** [comment]
OK - I have been playing a bit more around. The documentation states:

```
Make requests from Home Assistant like this:

curl --cacert /share/tesla/selfsigned.pem \
    --header "Authorization: Bearer $TESLA_AUTH_TOKEN" \
    "https://addon-tesla-http-proxy/api/1/vehicles"
```

However, the Flask application returns a refresh token and a client id - not an access token. I seem to remember that previous versions of your addon returned an access token (a very, very long token), which is what I used to test. That token was most likely expired. Is it correctly understood, that the addon doesn't currently return a working access token, and relies on other applications (like the Custom Tesla addon from HACS) to utilize the refresh token + client ID to obtain an access token (with a limited lifetime)?

**Comment by llamafilm** [comment]
That's exactly right.  Over time, I'm trying to refine this to be more user friendly, and less of a developer tool.  I removed the access token to declutter the output because I assume most users will just want to use this with the Tesla integration.  I've submitted a PR for the Tesla component to work with this but it's still a work in progress.  I guess I should clarify the docs here.  Maybe I should add a `debug` config option to enable debug logging?

If you want to test with curl, you can refresh the token like this.  (From https://developer.tesla.com/docs/fleet-api#authentication)
```sh
curl --request POST \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'grant_type=refresh_token' \
  --data-urlencode "client_id=$CLIENT_ID" \
  --data-urlencode "refresh_token=$REFRESH_TOKEN" \
  'https://auth.tesla.com/oauth2/v3/token'
```

**Comment by janchrillesen** [comment]
Thanks again. Now everything works, and I get a reply from the API

(TMY SR 2023 in EU)
