### ISSUE TITLE
Port conflict with GivTCP, 502 Bad Gateway

### ISSUE THREAD

**Issue by Kureigu07** [llamafilm/tesla-http-proxy-addon#73]
### The problem

This add-on appears to use port 8099 for the flask web-ui, however the add-on GivTCP also uses the same port for a web interface. Neither add-ons allow this port to be configured, which I believe is resulting in a 502 error and  "Fix public key before proceeding."

### What version of the addon are you using?

2.2.3

### What version of Home Assistant Core are you using?

core-2024.3.3

### What type of installation are you running?

Home Assistant OS

### What version of Tesla integration are you using?

v3.20.5

### What region of Tesla API are you using?

Europe, Middle East

### What model and year is your vehicle?

Y 23

### What is your domain name (FQDN)?

nocnbots.duckdns.org

### Paste the log output from the addon here

```text
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service webui: starting
s6-rc: info: service webui successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[19:27:19] webui:INFO: Starting Flask server for Web UI...
[19:27:19] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.30.33.9:8099
[19:27:19] werkzeug:INFO: Press CTRL+C to quit
[19:27:20] INFO: Found existing keypair
[19:27:20] INFO: Testing public key...
HTTP/2 404 
server: nginx
date: Tue, 02 Apr 2024 18:27:21 GMT
content-type: text/plain; charset=utf-8
content-length: 14
referrer-policy: no-referrer
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=31536000; includeSubDomains

[19:27:21] FATAL: Fix public key before proceeding.
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service webui: stopping
s6-rc: info: service webui successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

**Comment by baylanger** [comment]
Couldn’t resist …. Maybe this add-on should use port 7399 (S3XY) 😂

**Comment by llamafilm** [comment]
Port 8099 is not exposed outside the docker network, it's only available through Home Assistant ingress.  So it will not cause a conflict.
Read through the discussions.  There are many other users having trouble with their public key, and it's almost always caused by some problem with your domain, DNS, or TLS certificate.
